version: "3"
services:
  ifmysql:
    restart: always
    image: mysql:5.7
    container_name: ifmysql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
      - "3306:3306"

  ifredis:
    restart: always
    image: redis:latest
    container_name: ifredis
    ports:
      - "6379:6379"